version: '3.9'

services:
  redis:
    image: redis:7
    container_name: redis
    command: ['redis-server', '--appendonly', 'yes']
    ports:
      - '6379:6379'
    volumes:
      - ./data/redis:/data
    restart: unless-stopped

  mongo:
    image: mongo:7
    container_name: mongo
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: strong_mongo_password
    ports:
      - '27017:27017'
    volumes:
      - ./data/mongo:/data/db
    restart: unless-stopped

  redisinsight:
    image: redislabs/redisinsight:latest
    container_name: redisinsight
    ports:
      - '8001:8001'
    restart: unless-stopped
